project_id = "roomswap"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = []
jwt_expiry = 3600
enable_signup = false

[auth.email]
enable_signup = false
enable_confirmations = false

[functions]
[functions.replace]
verify_jwt = true

[functions.create-sub-account]
verify_jwt = true
